exclude = [
    ".git",
    ".vscode",
    ".ruff_cache",
    ".venv",
    "venv",
]
line-length = 88
indent-width = 4

[lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]

[format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"

docstring-code-format = false
docstring-code-line-length = "dynamic"